### ISSUE TITLE
Fails to build with the latest release glfw-3.4

### ISSUE THREAD

**Issue by yurivict** [mitsuba-renderer/nanogui#193]
```
FAILED: [code=1] CMakeFiles/nanogui.dir/src/chroma.cpp.o 
/usr/local/libexec/ccache/c++ -DNANOGUI_BUILD -DNANOGUI_SHARED -DNANOGUI_USE_OPENGL -DNFD_PORTAL -DNVG_BUILD -DNVG_SHARED -I/usr/ports/x11-toolkits/nanogui/work/.build -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/ext/nanobind/ext/robin_map/include -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/include -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/ext/nanovg/src -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/ext/nativefiledialog-extended/src/include -isystem /usr/local/include -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wextra -stdlib=libc++ -D_LIBCPP_VERSION -O2 -pipe -fstack-protector-strong -fno-strict-aliasing    -DNDEBUG -std=gnu++17 -flto -fPIC -fvisibility=hidden -MD -MT CMakeFiles/nanogui.dir/src/chroma.cpp.o -MF CMakeFiles/nanogui.dir/src/chroma.cpp.o.d -o CMakeFiles/nanogui.dir/src/chroma.cpp.o -c /usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/src/chroma.cpp
/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/src/chroma.cpp:320:30: error: use of undeclared identifier 'glfwGetWindowPrimaries'
  320 |     return from_wp_primaries(glfwGetWindowPrimaries(screen->glfw_window()));
      |                              ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[ 50% 9/10] /usr/local/libexec/ccache/c++ -DNANOGUI_BUILD -DNANOGUI_SHARED -DNANOGUI_USE_OPENGL -DNFD_PORTAL -DNVG_BUILD -DNVG_SHARED -I/usr/ports/x11-toolkits/nanogui/work/.build -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/ext/nanobind/ext/robin_map/include -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/include -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/ext/nanovg/src -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/ext/nativefiledialog-extended/src/include -isystem /usr/local/include -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wextra -stdlib=libc++ -D_LIBCPP_VERSION -O2 -pipe -fstack-protector-strong -fno-strict-aliasing    -DNDEBUG -std=gnu++17 -flto -fPIC -fvisibility=hidden -MD -MT CMakeFiles/nanogui.dir/src/imageview.cpp.o -MF CMakeFiles/nanogui.dir/src/imageview.cpp.o.d -o CMakeFiles/nanogui.dir/src/imageview.cpp.o -c /usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/src/imageview.cpp
[ 60% 9/10] /usr/local/libexec/ccache/c++ -DNANOGUI_BUILD -DNANOGUI_SHARED -DNANOGUI_USE_OPENGL -DNFD_PORTAL -DNVG_BUILD -DNVG_SHARED -I/usr/ports/x11-toolkits/nanogui/work/.build -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/ext/nanobind/ext/robin_map/include -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/include -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/ext/nanovg/src -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/ext/nativefiledialog-extended/src/include -isystem /usr/local/include -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wextra -stdlib=libc++ -D_LIBCPP_VERSION -O2 -pipe -fstack-protector-strong -fno-strict-aliasing    -DNDEBUG -std=gnu++17 -flto -fPIC -fvisibility=hidden -MD -MT CMakeFiles/nanogui.dir/src/common.cpp.o -MF CMakeFiles/nanogui.dir/src/common.cpp.o.d -o CMakeFiles/nanogui.dir/src/common.cpp.o -c /usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/src/common.cpp
FAILED: [code=1] CMakeFiles/nanogui.dir/src/common.cpp.o 
/usr/local/libexec/ccache/c++ -DNANOGUI_BUILD -DNANOGUI_SHARED -DNANOGUI_USE_OPENGL -DNFD_PORTAL -DNVG_BUILD -DNVG_SHARED -I/usr/ports/x11-toolkits/nanogui/work/.build -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/ext/nanobind/ext/robin_map/include -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/include -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/ext/nanovg/src -I/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/ext/nativefiledialog-extended/src/include -isystem /usr/local/include -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wextra -stdlib=libc++ -D_LIBCPP_VERSION -O2 -pipe -fstack-protector-strong -fno-strict-aliasing    -DNDEBUG -std=gnu++17 -flto -fPIC -fvisibility=hidden -MD -MT CMakeFiles/nanogui.dir/src/common.cpp.o -MF CMakeFiles/nanogui.dir/src/common.cpp.o.d -o CMakeFiles/nanogui.dir/src/common.cpp.o -c /usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/src/common.cpp
/usr/ports/x11-toolkits/nanogui/work/nanogui-0.2.0-112-gfce17b8/src/common.cpp:69:22: error: use of undeclared identifier 'GLFW_WAYLAND_COLOR_MANAGEMENT'
   69 |         glfwInitHint(GLFW_WAYLAND_COLOR_MANAGEMENT, GLFW_TRUE);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

FreeBSD 15.1 STABLE
