### PR TITLE
fix OpenGL link error

### LINKED ISSUE #25: Build problems
Hi!  Seeing the following errors when trying a straight compile on Ubuntu with GCC 9.2.1:

[ 69%] Linking CXX executable example3
/usr/bin/ld: /tmp/example3.AIsY20.ltrans0.ltrans.o: undefined reference to symbol 'glViewport'
/usr/bin/ld: /lib/x86_64-linux-gnu/libGL.so.1: error adding symbols: DSO missing from command line

### PR DESCRIPTION
**Pull request by bcumming**
Ensure that the OpenGL library is linked correctly for `example3` on Linux systems.

Fixes #25.

### CODE REVIEW

**Comment by bcumming** [comment]
I will close this, because #24 addresses the same error.
